CREATE TABLE LEAVE_DETAILS(
 LEV_ID VARCHAR(30) PRIMARY KEY,
 LEV_NOD INT NOT NULL,
 LEV_SDT DATE,
 LEV_EDT DATE,
 LEV_TYPE VARCHAR(20) NOT NULL DEFAULT 'EL',
 LEV_STATUS VARCHAR(20) NOT NULL DEFAULT 'NOT APPLIED',
 LEV_REASON VARCHAR(20) NOT NULL,
 LEV_ADT DATE ,
 LEV_CMT VARCHAR(20),
 EMP_ID INT,
 foreign key(EMP_ID) references Employee(EMP_ID));
 
